#   [program:finesheet-queue-orders]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/finesheet/artisan queue:work --queue=orders,orders-low --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/finesheet/storage/logs/queue-orders-%(process_num)02d.log
stopwaitsecs=3600
